networks:
    st_network:
        driver: bridge

services:
    bot:
        build:
            context: ./bot
        restart: unless-stopped
        networks:
            - st_network
        
    api:
        build:
            context: ./backend
        restart: unless-stopped
        networks:
            - st_network
        ports:
            - "8080:8080"